In [1]:
import pandas as pd
import sys

sys.path.append("../src")

from skill_extractor import extract_skills

In [2]:
df = pd.read_csv("../data/sample_inputs/sample_job_descriptions.csv")
df.head()

   job_id                                    job_description
0       1  We are looking for a Data Analyst with strong ...
1       2  We are hiring a Data Scientist with experience...
2       3  Seeking a Data Engineer with expertise in ETL ...
3       4  We need a Machine Learning Engineer who can de...

In [3]:
df["extracted_skills"] = df["job_description"].apply(extract_skills)
df[["job_id", "extracted_skills"]]

   job_id                                   extracted_skills
0       1                 [dashboards, excel, power bi, sql]
1       2  [machine learning, model development, python, ...
2       3      [aws, cloud, etl, spark, workflow automation]
3       4      [cloud, machine learning, python, tensorflow]

In [4]:
df["num_skills_found"] = df["extracted_skills"].apply(len)
df[["job_id", "num_skills_found", "extracted_skills"]]

   job_id  num_skills_found                                   extracted_skills
0       1                 4                 [dashboards, excel, power bi, sql]
1       2                 5  [machine learning, model development, python, ...
2       3                 5      [aws, cloud, etl, spark, workflow automation]
3       4                 4      [cloud, machine learning, python, tensorflow]